//! TTT Kernel Infrastructure
//!
//! This crate provides the core kernel traits and implementations:
//! - `FusedKernel` - trait for defining fused `CubeCL` kernels
//! - `FusedKernelBackend` - backend trait for kernel implementations
//! - `TensorBundle` - generic trait for tensor bundles
//! - GELU activation kernels

#![warn(clippy::pedantic)]
#![allow(
    // names like xq, xv, xk trigger this
    clippy::similar_names,
    // generally intended
    clippy::too_many_arguments,
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_possible_wrap,
    // complexity
    clippy::too_many_lines,
    clippy::type_complexity,
    // generated by cubecl macro
    clippy::format_push_string,
    clippy::trivially_copy_pass_by_ref,
    // we want some acronym names like RvFCs which trigger these.
    non_camel_case_types,
    non_snake_case,
)]

/// Launch a `CubeCL` kernel with bounds checking in debug builds,
/// unchecked in release builds for performance. Must be called inside `unsafe`.
macro_rules! cube_launch {
    ($kernel:ident :: < $($ty:ty),+ > ( $($args:expr),* $(,)? )) => {{
        #[cfg(debug_assertions)]
        { $kernel::launch::< $($ty),+ >( $($args),* ).unwrap() }
        #[cfg(not(debug_assertions))]
        { $kernel::launch_unchecked::< $($ty),+ >( $($args),* ).unwrap() }
    }};
}

pub mod bundle;
pub mod gelu;
mod gelu_tanh;
pub mod impls;
pub mod kernel;
pub mod util;

// Re-export commonly used items
pub use bundle::TensorBundle;
pub use gelu::{GeluBwdKernel, GeluInput, GeluOutput, GeluTanhKernel, gelu_bwd, gelu_tanh};
pub use kernel::{FusedKernel, FusedKernelBackend};
